import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainNav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Hunting Coder
        </h1>
        <p className={styles.description}>
         A blog for hunting coders by a hunting coder
        </p>

        <div className={styles.blog}>
         <div className={styles.blogItem}>
          <h3>How to learn Javascript in 2022?</h3>
          <p>For sure there is no universal best practice that you can apply to every business and application but for the productive codebase, we can follow some general rules. </p>
         </div>
        </div>  <div className={styles.blog}>
         <div className={styles.blogItem}>
          <h3>How to learn Javascript in 2022?</h3>
          <p>For sure there is no universal best practice that you can apply to every business and application but for the productive codebase, we can follow some general rules. </p>
         </div>
        </div>   
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
